services:
  flash-forge:
    image: nathan5471/flash-forge:latest
    container_name: flash-forge
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/flash-forge
      - FRONTEND_URL=
      - JWT_SECRET=
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flash-forge
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
